version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.2
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=MASTER_KEY
    volumes:
      - ./meili_data:/meili_data
